### ISSUE TITLE
Trouble with language pack

### ISSUE THREAD

**Issue by jeckyl** [merchantsedition/merchantsedition#1]
Hi,

I have just installed version 1.9.0 which is identified as a Thirtybees 1.1.1 which raises a concern in the management of languages since these packages do not exist at the level of the servers of thirtybees.

![error-merchantedition-install-french](https://user-images.githubusercontent.com/595633/103787835-6a818680-503e-11eb-818b-3cc432cf2782.png)
![error-ad-lang-pack](https://user-images.githubusercontent.com/595633/103787836-6b1a1d00-503e-11eb-9762-3bf2e0c076fb.png)

**Comment by merchantsedition** [comment]
This is expected, unfortunately. As this release is literally a build from thirty bees sources, it also attempts to fetch language packages from thirty bees servers. As thirty bees didn't make such a release, they also have no language pack for their v1.1.1.

This problem will go away as soon as Merchant's Edition provides its own language pack servers and directs the installer to use this one, which is expected to happen with release Merchant's Edition 1.9.1, in about three weeks.

**Comment by jeckyl** [comment]
Thank you for these precisions, it was just to draw attention to this point because it is not easy to test everything completely.

Thanks for all the work done on this version.

**Comment by merchantsedition** [comment]
Just for completeness: this issue should be fixed with the 1.9.1 release.
