### ISSUE TITLE
Issue during "Install modules"

### ISSUE THREAD

**Issue by M4ketech** [merchantsedition/merchantsedition#2]
An error occurred during installation...

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.
`
Uncaught Error: Class 'HomeSlide' not found in /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/modules/homeslider/homeslider.php:131 Stack trace: #0 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/modules/homeslider/homeslider.php(115): HomeSlider->installSamples() #1 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/models/install.php(797): HomeSlider->install() #2 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/controllers/http/process.php(283): InstallModelInstall->installModules(Object(HomeSlider)) #3 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/controllers/http/process.php(103): InstallControllerHttpProcess->processInstallModules() #4 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/classes/controllerHttp.php(203): InstallControllerHttpProcess->process() #5 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/trystart.php(30): InstallControllerHttp::execute() #6 /var/www/vhosts/arcticaspen.hostaan.cc/httpdocs/install/index.php(52): require_once('/var/www/vhosts...') #7 `

**Comment by merchantsedition** [comment]
This looks much like files uploaded for installation are incomplete. Happens surprisingly often and is a fault of the file uploading software. Uploading again should solve the problem.

The missing class is in `modules/homeslider/HomeSlide.php`, if this matters.

**Comment by M4ketech** [comment]
Moving shop via .zip and unzipping it on the server fixed the problem
